services:
  app:
    # Build the Docker image from the Dockerfile in the current directory.
    build: .
    container_name: strichliste-app
    restart: unless-stopped

    ports:
      - "3000:3000"

    # Volume mounting for persistent data.
    volumes:
      # Mounts the local './storage' directory to '/app/storage' in the container for image uploads.
      - ./storage:/app/storage
      # Mounts the local './db' directory to '/app/db' in the container for your database files.
      - ./db:/app/

    # --- Option 1: Load environment variables from a .env file (Recommended) ---
    # Docker Compose will automatically look for a file named '.env' in the same directory.
    env_file:
      - .env

    # --- Option 2: Define environment variables directly (Alternative) ---
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3000
    #   - DATABASE_PATH=/app/db/your_database_name.sqlite
    #   - ANOTHER_SECRET=some_value
