module.exports = {
    "/setup": ["Setup", "Error", "Page"],
    "/login": ["Login", "Error", "Page"],
    "/register": ["Setup", "Error", "Page"],
    "/overview": ["Overview", "Error", "Page", "Navbar", "Categories", "Items"],
    "/settings": ["Settings", "Error", "Page", "Setup", "Navbar", "Categories"],
    "/transaction_history": ["Items", "Error", "Page", "Navbar", "Items"],
    "/admin/index": ["Admin", "Error", "Page", "Setup", "Navbar", "Categories"],
    "/admin/items": ["Admin", "Error", "Page", "Setup", "Navbar", "Categories", "Items"],
    "/admin/categories": ["Admin", "Error", "Page", "Setup", "Navbar", "Categories"],
    "/admin/additems": ["Admin", "Error", "Page", "Setup", "Navbar", "Categories", "Items"],
    "/admin/settings": ["Admin", "Error", "Page", "Setup", "Navbar", "AdminSettings"],
    "/admin/users": ["Admin", "Error", "Page", "Setup", "Navbar", "AdminUsers"],
    "/admin/edituser": ["Admin", "Error", "Page", "Setup", "Navbar", "AdminUser"],
}